### ISSUE TITLE
node-sqlite3-wasm.d.ts missing

### ISSUE THREAD

**Issue by fprijate** [tndrle/node-sqlite3-wasm#14]
It would be nice to have d.ts file (maybe adapted sqlite3.d.ts) to omit warnings in VSC.
Or maybe @types/node-sqlite3-wasm ?

**Comment by tndrle** [comment]
Hi, I added type definitions in PR #19. However, I'm not sure whether the types are properly recognized by TypeScript. Maybe some kind of export is required. Any feedback is welcome.

**Comment by fprijate** [comment]
There is a new, IMHO correct PR. Sorry for the old one.

**Comment by tndrle** [comment]
Done in #19
