### ISSUE TITLE
Include FTS5 extension

### ISSUE THREAD

**Issue by jbaiter** [tndrle/node-sqlite3-wasm#45]
It would be great if the SQLite build could include the FTS5 extension to support use cases that need fulltext search support.
It should be enough include `-DSQLITE_ENABLE_FTS5` in [`SQLITE_FLAGS`](https://github.com/tndrle/node-sqlite3-wasm/blob/main/Makefile#L12)

**Comment by tndrle** [comment]
Thanks for the request. The new v0.8.0 supports it.

**Comment by phil294** [comment]
This is wonderful, thank you so much for your efforts and the concise documentation @tndrle! It seems that SQLite+FTS+wasm is now the all-around best portable full text search toolset for Node. I have [ported](https://github.com/phil294/search-plus-plus-vscode-extension/commit/5e803e8b7a371fbf093535507614b1983959203d#diff-c0f0d367a0c708cbd2a5b5b2e29e31a9ef126a9e1531018f5d6c1291382752ed) my wip VSCode [extension](https://github.com/phil294/search-plus-plus-vscode-extension) (thus the need for cross-platformness) from [search-index](https://github.com/fergiemcdowall/search-index) to node-sqlite3-wasm and got an immediate speed boost by factor ~10.
