### ISSUE TITLE
[feature request] add support for `returing`

### ISSUE THREAD

**Issue by subframe7536** [tndrle/node-sqlite3-wasm#47]
Thanks for your great work!

I'm writing a dialect for Kysely, that needs get `lastInsertRowid`, `changes` and rows when the sql have `returing`, but in my current(v0.8.0) try:

```ts
import sqlite from "node-sqlite3-wasm";

const db = new sqlite.Database(':memory:')

db.run('create table test1(a INTEGER, b TEXT)')

console.log(db.run('insert into test1(a, b) values (1, \'test\') returning *'))
// { changes: 0, lastInsertRowid: 1 }

console.log(db.exec('insert into test1(a, b) values (1, \'test\') returning *'))
// undefined

console.log(db.prepare('insert into test1(a, b) values (1, \'test\') returning *').all())
// [{ a: 1, b: 'test' }], but no changes and lastInsertRowid
```

maybe expose a new API or just expose `sqlite.changes()`?

**Comment by tndrle** [comment]
Hi, `.all()` returns an array and the length of the array equals `changes`. So if you can live without `lastInsertRowid`, this would be a solution. If you need `lastInsertRowid` as well, I do not have quick a solution.

For the moment and unless there are more requests in this direction, I will not implement anything to solve this.

**Comment by subframe7536** [comment]
Thanks for your reply!

Finally i implement it by checking if sql string has `returning`. If true, call `db.all(sql, params)` to get rows and `db.get('select last_insert_rowid() as id').id` to get `lastInsertRowid`

**Comment by subframe7536** [comment]
find another way right now: call `db.all(sql, params)` to get rows and `db.run('select 1')` to get `changes` and `lastInsertRowid`

**Comment by tndrle** [comment]
Happy you found a solution. `db.get('select last_insert_rowid() as id').id` is nice 🙂
