### ISSUE TITLE
can it encrypt the .db file ?

### ISSUE THREAD

**Issue by gzcz** [tndrle/node-sqlite3-wasm#84]
like sqlcipher to encrypt the database .db file.  
example code: 
`javascript
const { Database } = require("node-sqlite3-wasm");\n
const db = new Database("database.db");\n
db.run("pragma key = 'secret'");\n
db.run("pragma cipher = 'aes-256-cbc'");//optional, default cipher be eqaul to 'aes-256-cbc'\n
`

**Comment by tndrle** [comment]
Hi, no that's not possible
